#include <cstdio>
#include <cstdlib>
#include <iostream>

// function pointer used for f(comp,time,vector);
using fptr = double(int, double, double *);

/*******************************************************************************

The structure EDM_Data is created in order to contain data generated by nume-
rical integration, and Fourier Analysis. It contains information of sampling
frequency, generated data.

Member function initialize is used to initialize structure.

*******************************************************************************/

struct EOM_Data{

  int dim;
  int NSTEP;
  double dt;
  double t0;
  double *init_data;
  double *motion;
  double *dft_decomp;

  EOM_Data() {
    dim = 2;
    NSTEP = 1000;
    dt = 0.01;
    t0 = 0.0;
  };

  void initialize(int n, int N, double delta, double t_init);
  void kill();
  void WriteCoord(int i, int j, double x);
  double ReadCoord(int i, int j);
  void rk4_integration(fptr f);

};

 /******************************************************************************

 Implementation of elemntary Member functions used to simplify complex integra-
 tion routines.

 ******************************************************************************/

 void EOM_Data::initialize(int n, int N, double delta, double t_init){
   if(0 < n && 0 < N && 0 < delta){
     NSTEP = N;
     dim = n;
     dt = delta;
     t0 = t_init;
     init_data = (double*) calloc(dim,sizeof(double));
     motion = (double*) calloc(dim*NSTEP,sizeof(double));
   }
   else
     std::cerr << "Inappropriate initialization" << '\n';
 }

 void EOM_Data::kill(){
   free(init_data);
   free(motion);
   free(dft_decomp);
 }

 void EOM_Data::WriteCoord(int i, int j, double x){
   if(i < NSTEP && j < dim)
     motion[dim*i+j] = x;
   else
     std::cerr << "Writing Outside Array" << '\n';
 }

 double EOM_Data::ReadCoord(int i, int j){
   if(i < NSTEP && j < dim)
     return motion[dim*i+j];
   else{
     std::cerr << "Reading Outside Array" << '\n';
     return 0.0;
   }
 }
